#
# ~/.basrhc
#

# If not running interractively, don't do anything
[[ $- != *i* ]] && return

# Add git information
source ~/.git_prompt

# Prompt
PS1='\e[0;32m\u@\h\e[0m \e[0;33m\W\e[0m \e[0;36m$(__git_ps1)\e[0m\n\$ '

# Aliases
alias ls='ls --color=auto' 
